version: '3.8'

services:
  spring-ai-app:
    build: .
    container_name: spring-ai-app
    ports:
      - "8080:8080"
    env_file:
      - .env.example
    depends_on:
      - postgres-db

  postgres-db:
    image: postgres:15
    container_name: postgres-db
    ports:
      - "5432:5432"
    env_file:
      - .env.example
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
